import NavBar from './components/navBar/NavBar.jsx'
import './layout.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />

        <div className="container">{children}</div>
      </body>
    </html>
  )
}
